fix10?

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -132,8 +132,14 @@ jobs:
               MODEL_HEALTH_STATUS=$(docker inspect --format='{{.State.Health.Status}}' nilai-llama_1b_gpu 2>/dev/null)
               ATTEMPT=$((ATTEMPT + 1))
           done
+          echo "API_HEALTH_STATUS: $API_HEALTH_STATUS"
           if [ $API_HEALTH_STATUS != "healthy" ]; then
               echo "Error: nilai-api failed to become healthy after $MAX_ATTEMPTS attempts"
+              exit 1
+          fi
+          echo "MODEL_HEALTH_STATUS: $MODEL_HEALTH_STATUS"
+          if [ $MODEL_HEALTH_STATUS != "healthy" ]; then
+              echo "Error: nilai-llama_1b_gpu failed to become healthy after $MAX_ATTEMPTS attempts"
               exit 1
           fi
           export AUTH_TOKEN=$(docker exec nilai-api uv run src/nilai_api/commands/add_user.py --name test1 --email test1@test.com --ratelimit-minute 1000 --ratelimit-hour 1000 --ratelimit-day 1000 | jq ".apikey" -r)
