fix: various fixes to vllm Dockerfile, versions and ci file
Co-authored-by: Sergio Medina <lumasepa@gmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -38,7 +38,7 @@ jobs:
 
       - name: Run tests
         run: uv run pytest -v tests/unit
-        
+
       # - name: pyright
       #   run: uv run pyright nilai-api
 
@@ -63,7 +63,7 @@ jobs:
           github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
           runners-per-machine: 1
           number-of-machines: 1
-          ec2-image-id: ami-0e53ca906f30585ea
+          ec2-image-id: ami-0ac221d824dd88706
           ec2-instance-type: g4dn.xlarge
           subnet-id: subnet-0ec4c353621eabae2
           security-group-id: sg-03ee5c56e1f467aa0
@@ -103,31 +103,63 @@ jobs:
         run: docker build -t nillion/nilai-api:latest -f docker/api.Dockerfile --target nilai .
 
       - name: Create .env
-        run: cp .env.sample .env
+        run: |
+         cp .env.ci .env
+         # Copy secret into .env replacing the existing HF_TOKEN
+         sed -i 's/HF_TOKEN=.*/HF_TOKEN=${{ secrets.HF_TOKEN }}/' .env
 
       - name: Start Services
         run: |
           docker-compose -f docker-compose.yml \
           -f docker-compose.dev.yml \
-          -f docker/compose/docker-compose.llama-3b-gpu.yml \
-          -f docker/compose/docker-compose.llama-8b-gpu.yml \
+          -f docker/compose/docker-compose.llama-1b-gpu.ci.yml \
           up -d
+          docker ps -a
 
       - name: Run E2E tests
         run: |
           set -e
-          sleep 30 # wait for tables in bbdd to be created to be able to add the user
-          
-          export AUTH_TOKEN=$(docker exec nilai-api uv run src/nilai_api/commands/add_user.py --name test1 --email test1@test.com | jq ".apikey")
+          # Wait for the services to be ready
+          API_HEALTH_STATUS="unhealthy"
+          MODEL_HEALTH_STATUS="unhealthy"
+          MAX_ATTEMPTS=20
+          ATTEMPT=1
+
+          # Keep the container running
+          # while true; do sleep 30; done
+
+          while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
+              echo "Waiting for nilai to become healthy... API:[$API_HEALTH_STATUS] MODEL:[$MODEL_HEALTH_STATUS] (Attempt $ATTEMPT/$MAX_ATTEMPTS)"
+              sleep 30
+              API_HEALTH_STATUS=$(docker inspect --format='{{.State.Health.Status}}' nilai-api 2>/dev/null)
+              MODEL_HEALTH_STATUS=$(docker inspect --format='{{.State.Health.Status}}' nilai-llama_1b_gpu 2>/dev/null)
+
+              if [ "$API_HEALTH_STATUS" = "healthy" ] && [ "$MODEL_HEALTH_STATUS" = "healthy" ]; then
+                  break
+              fi
+
+              ATTEMPT=$((ATTEMPT + 1))
+          done
+          echo "API_HEALTH_STATUS: $API_HEALTH_STATUS"
+          if [ $API_HEALTH_STATUS != "healthy" ]; then
+              echo "Error: nilai-api failed to become healthy after $MAX_ATTEMPTS attempts"
+              exit 1
+          fi
+          echo "MODEL_HEALTH_STATUS: $MODEL_HEALTH_STATUS"
+          if [ $MODEL_HEALTH_STATUS != "healthy" ]; then
+              echo "Error: nilai-llama_1b_gpu failed to become healthy after $MAX_ATTEMPTS attempts"
+              exit 1
+          fi
+          export AUTH_TOKEN=$(docker exec nilai-api uv run src/nilai_api/commands/add_user.py --name test1 --email test1@test.com --ratelimit-minute 1000 --ratelimit-hour 1000 --ratelimit-day 1000 | jq ".apikey" -r)
           export ENVIRONMENT=ci
           uv run pytest -v tests/e2e
 
       - name: Stop Services
-        run: docker-compose -f docker-compose.yml \
+        run: |
+          docker-compose -f docker-compose.yml \
           -f docker-compose.dev.yml \
-          -f docker/compose/docker-compose.llama-3b-gpu.yml \
-          -f docker/compose/docker-compose.llama-8b-gpu.yml \
-          down
+          -f docker/compose/docker-compose.llama-1b-gpu.ci.yml \
+          down -v
 
   stop-runner:
     name: Stop self-hosted EC2 runner
